/* Browser UI. Financial data stays in memory unless the user explicitly saves it. */
(() => {
  'use strict';
  const E=window.WealthEngine, $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
  const money=new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0});
  const num=new Intl.NumberFormat('id-ID',{maximumFractionDigits:1});
  const fmt=v=>Number.isFinite(v)?money.format(Math.round(v)):'Perlu ditinjau';
  const short=v=>!Number.isFinite(v)?'—':Math.abs(v)>=1e12?'Rp'+num.format(v/1e12)+' T':Math.abs(v)>=1e9?'Rp'+num.format(v/1e9)+' M':Math.abs(v)>=1e6?'Rp'+num.format(v/1e6)+' jt':fmt(v);
  const pc=v=>Number.isFinite(v)?num.format(v)+'%':'—';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const icon=name=>window.TSUi?.icon(name)||'';
  const LABEL={house:'Rumah / DP',education:'Pendidikan',wedding:'Pernikahan',retirement:'Pensiun',holiday:'Liburan',other:'Tujuan lain'};
  const STORE='taktiksaham.wealth.v1';
  let state=E.example(38), step=0, result=null, selectedGoal=null, toastTimer;
  const pathGet=path=>path.split('.').reduce((v,k)=>v?.[k],state);
  const pathSet=(path,value)=>{const keys=path.split('.');let obj=state;for(const key of keys.slice(0,-1))obj=obj[key];obj[keys.at(-1)]=value;};
  const labelAsset=id=>E.ASSETS.find(x=>x.id===id).name+(state.preference==='syariah'&&id!=='cash'?' (syariah)':'');
  function toast(text){clearTimeout(toastTimer);$('#wmToast').textContent=text;toastTimer=setTimeout(()=>{$('#wmToast').textContent='';},5500);}
  function field(label,path,opts={}) {
    const val=pathGet(path), id='f-'+path.replaceAll('.','-');
    let control;
    if(opts.options)control=`<select id="${id}" data-path="${path}">${opts.options.map(([v,t])=>`<option value="${esc(v)}" ${String(v)===String(val)?'selected':''}>${esc(t)}</option>`).join('')}</select>`;
    else control=`<input id="${id}" data-path="${path}" type="${opts.text?'text':'number'}" ${opts.text?'maxlength="80"':`inputmode="${opts.money?'numeric':'decimal'}" min="${opts.min??0}" max="${opts.max??(opts.money?1e13:100)}" step="${opts.step??(opts.money?100000:1)}"`} value="${esc(val)}" ${opts.help?`aria-describedby="${id}-help"`:''}>`;
    return `<label class="wm-field ${opts.wide?'wide':''}" for="${id}"><span>${esc(label)}</span>${control}${opts.help?`<small id="${id}-help">${esc(opts.help)}</small>`:''}${opts.money?`<small class="money-line" data-money-for="${path}">${fmt(Number(val))}</small>`:''}</label>`;
  }
  const card=(name,desc,body,ico='grid',wide=false)=>`<section class="wm-card ${wide?'wide':''}"><div class="wm-card-head">${icon(ico)}<div><h3>${name}</h3>${desc?`<p>${desc}</p>`:''}</div></div>${body}</section>`;
  function sectionTitle(title,desc){return `<div class="wm-section-title"><div><h2>${title}</h2><p>${desc}</p></div></div>`;}
  function finances(){
    const f=E.foundation(state);
    return sectionTitle('Kenali posisi keuangan hari ini.','Seluruh nominal dalam rupiah. Isi angka bulanan untuk penghasilan, pengeluaran, dan cicilan.')+
      `<div class="wm-form-grid">${card('Profil nasabah','Gunakan alias bila tidak ingin mencantumkan nama.',`<div class="wm-fields">${field('Nama rencana / alias','alias',{text:true,wide:true})}${field('Usia saat ini','age',{min:17,max:60,help:'Rentang usia simulator 17–60 tahun.'})}${field('Jumlah tanggungan','dependents',{max:15})}${field('Sumber penghasilan','incomeType',{options:[['stable','Tetap / relatif stabil'],['variable','Usaha / tidak tetap'],['retired','Pensiun / memakai hasil aset'],['student','Pelajar / belum berpenghasilan']]})}${field('Preferensi instrumen','preference',{options:[['all','Konvensional / tanpa pembatasan'],['syariah','Instrumen syariah']]})}</div>`,'profile')}
      ${card('Arus kas bulanan','Anggaran investasi harus berasal dari surplus.',`<div class="wm-fields">${field('Penghasilan bersih per bulan','income',{money:true})}${field('Pengeluaran per bulan','expenses',{money:true,help:'Termasuk kebutuhan, gaya hidup, dan premi; di luar cicilan serta investasi.'})}${field('Total cicilan per bulan','debtPayment',{money:true})}${field('Setoran rutin direncanakan sampai usia','contributionEndAge',{min:state.age,max:100,help:'Sesudah usia ini tidak ada setoran baru; aset tujuan tetap diproyeksikan tumbuh. Sesuaikan dengan akhir penghasilan / pensiun.'})}${field('Anggaran menabung / investasi','budget',{money:true,help:'Termasuk pengisian dana darurat. Sistem membatasi ke surplus yang tersedia.'})}</div>`,'fund')}
      ${card('Dana darurat & proteksi','Cadangan ini dipisahkan dari dana setiap tujuan.',`<div class="wm-fields">${field('Dana darurat yang sudah dipisahkan','emergency',{money:true,help:'Jangan masukkan lagi nominal ini ke daftar aset investasi di bawah.'})}${field('Target cadangan, dalam bulan','emergencyMonths',{min:1,max:24,help:'Acuan awal 3–6 bulan; tanggungan atau penghasilan tidak tetap dapat memerlukan lebih besar.'})}${field('Perlindungan kesehatan','healthCover',{options:[['yes','Ada, manfaat sudah ditinjau'],['review','Ada, manfaat perlu ditinjau'],['no','Belum ada']]})}${field('Proteksi jiwa bagi pencari nafkah','lifeCover',{options:[['yes','Ada, manfaat sudah ditinjau'],['review','Perlu ditinjau / belum yakin'],['no','Belum ada'],['na','Tidak relevan saat ini']]})}</div>`,'shield')}
      ${card('Kewajiban & aset lain','Aset noninvestasi dihitung untuk kekayaan bersih.',`<div class="wm-fields">${field('Total sisa utang','debtBalance',{money:true,help:'Saldo pokok seluruh utang, bukan jumlah cicilan bulanan.'})}${field('Nilai aset noninvestasi','otherAssets',{money:true,help:'Contoh rumah tinggal atau kendaraan. Tidak digunakan otomatis sebagai modal tujuan.'})}<label class="wm-check wm-field wide"><input type="checkbox" data-path="debtPriority" ${state.debtPriority?'checked':''}><span>Ada tunggakan atau utang konsumtif yang perlu diprioritaskan.</span></label></div>`,'file')}
      ${card('Aset yang tersedia untuk rencana','Isi nilai pasar saat ini, di luar dana darurat di atas. Hanya masukkan aset yang boleh digunakan untuk tujuan.',`<div class="wm-fields three">${E.ASSETS.map(a=>field(a.name,'assets.'+a.id,{money:true})).join('')}</div><p class="wm-subtle">Kekurangan dana darurat disisihkan dari kas terlebih dahulu, lalu RDPU. Jika masih kurang, anggaran bulanan digunakan mengisi cadangan sebelum tujuan lain. Penjualan aset dan perpindahan dana tetap perlu kamu lakukan sendiri.</p>`,'table',true)}</div>
      <div class="wm-inline-summary" id="financeSummary">${financialSummary(f)}</div>`;
  }
  function financialSummary(f){return `<div class="wm-inline-stat"><small>Surplus sebelum investasi</small><b class="${f.surplus<0?'negative':''}">${fmt(f.surplus)}</b></div><div class="wm-inline-stat"><small>Target dana darurat</small><b>${fmt(f.reserveTarget)}</b></div><div class="wm-inline-stat"><small>Modal tersedia setelah cadangan</small><b>${fmt(f.investable)}</b></div>`;}
  function goalFields(g,i){
    const p='goals.'+i+'.';
    return `<article class="wm-card"><div class="wm-goal-head"><div><div class="wm-goal-number">TUJUAN ${String(i+1).padStart(2,'0')}</div><h3>${esc(g.name)}</h3></div>${state.goals.length>1?`<button class="wm-remove" data-remove-goal="${i}">Hapus tujuan</button>`:''}</div><div class="wm-fields three">${field('Jenis tujuan',p+'type',{options:Object.entries(LABEL)})}${field('Nama tujuan',p+'name',{text:true})}${field('Prioritas',p+'priority',{options:[[1,'1 · Utama'],[2,'2 · Penting'],[3,'3 · Fleksibel']]})}
    ${g.type==='retirement'?`${field('Mulai pensiun pada usia',p+'retireAge',{min:state.age,max:80,help:'Boleh sama dengan usia saat ini jika sudah mulai pensiun.'})}${field('Simulasi sampai usia',p+'endAge',{min:g.retireAge+1,max:105,help:'Batas perencanaan, bukan prediksi usia hidup.'})}${field('Belanja pensiun bulanan, nilai hari ini',p+'spending',{money:true})}${field('Pendapatan pensiun lain per bulan',p+'pension',{money:true,help:'Nilai hari ini; diasumsikan ikut naik dengan inflasi tujuan.'})}`:`${field('Biaya tujuan dalam nilai hari ini',p+'amount',{money:true,min:1})}${field('Dibutuhkan dalam berapa tahun?',p+'years',{min:1/12,max:60,step:1/12,help:'Boleh pecahan, contoh 0,5 = enam bulan.'})}`}
    ${field('Inflasi tujuan per tahun (%)',p+'inflation',{max:15,step:0.1,help:'Asumsi, bukan perkiraan harga yang dijamin.'})}${field('Modal awal khusus tujuan ini',p+'seed',{money:true,help:'Bagian dari aset tersedia; jangan gunakan modal yang sama di dua tujuan.'})}</div></article>`;
  }
  function goalsForm(){const f=E.foundation(state),used=state.goals.reduce((n,g)=>n+g.seed,0);return sectionTitle('Susun tujuan, bukan sekadar produk.','Tambahkan hingga enam tujuan. Setiap tujuan memiliki tenggat, inflasi, modal, dan prioritas sendiri.')+`<div class="wm-capital-note">Modal tersedia <b>${fmt(f.investable)}</b> · dialokasikan ke tujuan <b>${fmt(used)}</b> · sisa <b>${fmt(f.investable-used)}</b><br>Prioritas utama didanai lebih dulu. Dalam prioritas yang sama, tenggat terdekat mendapat urutan lebih awal.</div><div class="wm-goals">${state.goals.map(goalFields).join('')}</div><div class="wm-goal-toolbar"><button class="button" id="addGoal" ${state.goals.length>=6?'disabled':''}>+ Tambah tujuan</button><span class="wm-subtle">Dana darurat sudah dihitung pada fondasi keuangan.</span></div>`;}
  const QUESTIONS=[
    ['loss','Penurunan sementara terbesar yang masih bisa kamu terima?',[[0,'Saya belum bersedia menerima penurunan nilai'],[5,'Sekitar 5% dari nilai investasi'],[10,'Sekitar 10%'],[20,'Sekitar 20%'],[35,'Sekitar 35% atau lebih, dengan memahami risikonya']]],
    ['reaction','Apa yang cenderung kamu lakukan saat pasar turun tajam?',[[0,'Segera mengurangi risiko agar tidak turun lebih jauh'],[1,'Menunggu sambil sangat membatasi penambahan risiko'],[2,'Mengevaluasi alasan investasi dan rencana awal'],[3,'Mengevaluasi, lalu mungkin menambah secara terukur']]],
    ['experience','Sejauh mana pengalaman investasimu?',[[0,'Belum pernah / baru mulai belajar'],[1,'Terbiasa tabungan, deposito, atau pasar uang'],[2,'Pernah memakai reksa dana atau obligasi'],[3,'Berpengalaman dalam saham dan pernah mengalami penurunan']]],
    ['goal','Apa prioritas utama saat berinvestasi?',[[0,'Menjaga modal dan kemudahan pencairan'],[1,'Pendapatan yang relatif stabil'],[2,'Keseimbangan antara pertumbuhan dan kestabilan'],[3,'Pertumbuhan jangka panjang dengan fluktuasi besar']]],
    ['fluctuation','Bagaimana kenyamananmu melihat nilai investasi berubah?',[[0,'Perubahan kecil pun membuat saya tidak nyaman'],[1,'Bisa menerima perubahan terbatas'],[2,'Bisa menerima perubahan cukup besar dengan rencana'],[3,'Bisa menerima perubahan besar untuk tujuan panjang']]],
    ['effort','Berapa waktu yang ingin kamu gunakan untuk mengelola investasi?',[[0,'Sangat terbatas; ingin proses sederhana'],[1,'Meninjau berkala, pengelolaan utama melalui profesional'],[2,'Bersedia mempelajari instrumen dan mengevaluasi rutin'],[3,'Aktif mempelajari emiten dan memantau portofolio']]]
  ];
  function riskForm(){return sectionTitle('Pahami kesediaan dan kemampuan mengambil risiko.','Jawab berdasarkan kondisi nyata. Pertanyaan ini membentuk model awal, bukan asesmen resmi pembukaan rekening.')+`<div class="wm-form-grid">${QUESTIONS.map(([key,q,options],i)=>`<section class="wm-card wm-question"><div class="wm-question-number">PERTANYAAN ${i+1} / 6</div><h3 id="q-${key}">${q}</h3><div class="wm-options" role="radiogroup" aria-labelledby="q-${key}">${options.map(([v,label])=>`<label class="wm-option"><input type="radio" name="risk-${key}" data-path="risk.${key}" value="${v}" ${state.risk[key]===v?'checked':''}><span>${label}</span></label>`).join('')}</div></section>`).join('')}</div><p class="wm-subtle">Setiap tujuan masih dibatasi jangka waktu. Penghasilan, cicilan, dana darurat, dan pengalaman dapat menurunkan tingkat risiko yang digunakan. Jawaban agresif tidak otomatis menghasilkan alokasi saham tinggi.</p>`;}
  function assumptionsForm(){return sectionTitle('Buka asumsi di balik setiap angka.','Angka awal merupakan contoh model yang dapat kamu ubah. Tidak memakai harga, kupon, atau kinerja produk terkini.')+`<div class="wm-assumption-note"><b>Return adalah asumsi nominal tahunan bersih.</b> Masukkan estimasi setelah biaya dan pajak yang relevan agar tidak menghitung hasil terlalu tinggi. Skenario tidak menggambarkan probabilitas; hasil nyata bisa berada di luar rentang.</div><div class="wm-form-grid">${card('Inflasi & masa pensiun','Inflasi tujuan dapat berbeda dari inflasi umum.',`<div class="wm-fields">${field('Inflasi umum per tahun (%)','assumptions.inflation',{max:15,step:0.1,help:'Dipakai untuk menunjukkan daya beli proyeksi dalam nilai uang hari ini.'})}${field('Return bersih masa pensiun (%)','assumptions.retirementReturn',{min:-10,max:20,step:0.1,help:'Asumsi terpisah untuk masa penarikan; cocokkan lagi dengan portofolio pensiun yang akan dipakai.'})}</div>`,'sliders',true)}</div><div class="wm-report-section"><div class="wm-table-wrap"><table class="wm-table"><caption class="sr-only">Asumsi return dan guncangan hipotetis per kelas instrumen</caption><thead><tr><th>Instrumen</th><th>Dasar / tahun</th><th>Rendah / tahun</th><th>Tinggi / tahun</th><th>Uji tekanan sekali</th></tr></thead><tbody>${E.ASSETS.map(a=>{const r=state.assumptions.returns[a.id];return `<tr><td><span class="wm-asset-label"><i class="wm-dot" style="background:${a.color}"></i>${esc(labelAsset(a.id))}</span></td><td><input aria-label="Return dasar ${esc(a.name)}" type="number" data-path="assumptions.returns.${a.id}" min="-20" max="30" step="0.1" value="${r}"></td><td data-low="${a.id}">${pc(r-E.LOW[a.id])}</td><td data-high="${a.id}">${pc(r+E.HIGH[a.id])}</td><td>${pc(E.SHOCK[a.id])}</td></tr>`;}).join('')}</tbody></table></div><p class="wm-subtle">Selisih skenario rendah/tinggi dan guncangan uji tekanan adalah pilihan ilustratif model. Kupon obligasi bukan total return; harga pembelian, pajak, biaya, reinvestasi, dan harga jual turut memengaruhi hasil.</p></div><div class="wm-assumption-note">Perhitungan tidak menaikkan return untuk mengejar target yang kekurangan dana. Kekurangan akan tetap terlihat agar kamu dapat meninjau modal, anggaran, biaya tujuan, atau tenggat yang memang fleksibel.</div>`;}
  function observations(r){const f=r.f,list=[];
    if(f.surplus<0)list.push(`Arus kas defisit ${fmt(-f.surplus)}/bulan. Periksa pengeluaran dan sumber pendanaan sebelum menambah setoran investasi.`);
    if(state.budget>f.budget)list.push(`Anggaran pilihan ${fmt(state.budget)} dibatasi menjadi ${fmt(f.budget)}/bulan sesuai surplus.`);
    if(f.debtRatio>0.3)list.push(`Cicilan mencapai ${pc(f.debtRatio*100)} dari penghasilan. Acuan 30% dipakai sebagai tanda untuk meninjau utang, bukan batas universal.`);
    if(state.debtPriority)list.push('Tinjau tunggakan / utang prioritas sebelum menambah investasi. Simulator tidak otomatis melunasi atau merestrukturisasi utang.');
    if(state.goals.some(g=>g.type==='retirement'&&state.contributionEndAge>g.retireAge))list.push('Usia akhir setoran melewati salah satu usia pensiun yang dipilih. Pastikan sumber penghasilan untuk setoran setelah pensiun memang tersedia.');
    if(state.dependents>0&&state.emergencyMonths<6)list.push('Ada tanggungan. Pertimbangkan apakah target dana darurat di bawah enam bulan cukup untuk situasimu.');
    if(state.incomeType==='variable'&&state.emergencyMonths<9)list.push('Penghasilan tidak tetap: uji kembali ketahanan cadangan terhadap beberapa bulan tanpa pemasukan.');
    if(state.healthCover!=='yes')list.push('Tinjau perlindungan kesehatan dan biaya yang belum ditanggung sebelum menambah risiko investasi.');
    if(state.dependents>0&&state.lifeCover!=='yes')list.push('Ada tanggungan: tinjau kebutuhan perlindungan pencari nafkah bersama profesional. Tidak ada estimasi premi otomatis.');
    if(state.age<18)list.push('Untuk usia 17 tahun, periksa persyaratan identitas dan pembukaan rekening melalui penyedia resmi. Simulator bukan verifikasi kelayakan rekening.');
    if(r.unassigned>1)list.push(`${fmt(r.unassigned)} aset belum ditetapkan ke tujuan. Tidak diberi pertumbuhan dalam proyeksi tujuan.`);
    if(!list.length)list.push('Arus kas dan data yang diisi memberi ruang perencanaan. Tetap tinjau perubahan kebutuhan, proteksi, dan risiko produk sebelum implementasi.');
    return list;
  }
  const detailList=rows=>`<ul class="wm-detail-list">${rows.map(([a,b])=>`<li><span>${a}</span><b>${b}</b></li>`).join('')}</ul>`;
  function profileCard(r){return `<section class="wm-card wm-report-card"><span class="eyebrow">PROFIL MODEL</span><div class="wm-profile-label">${r.risk.noRisk?'Fokus likuiditas':r.risk.label}</div><p>Hasil dibatasi kemampuan keuangan, toleransi rugi, dan jangka waktu masing-masing tujuan.</p><div class="wm-risk-bars" aria-label="Tingkat profil ${r.risk.level} dari 5">${[1,2,3,4,5].map(x=>`<span class="${x<=r.risk.level?'on':''}"></span>`).join('')}</div>${detailList([['Kesediaan mengambil risiko',E.LABELS[r.risk.willingness-1]],['Batas kemampuan keuangan',E.LABELS[r.risk.capacity-1]],['Toleransi penurunan yang diisi',pc(state.risk.loss)],['Kelola saham langsung?',state.risk.experience>=2&&state.risk.effort>=2?'Dapat dipertimbangkan sesuai tujuan':'Diarahkan ke reksa dana saham']])}${r.risk.reasons.length?`<ul class="wm-observations">${r.risk.reasons.map(t=>`<li>${esc(t)}</li>`).join('')}</ul>`:''}</section>`;}
  function emergencyCard(r){const f=r.f,covered=f.reserveTarget>0?Math.min(100,(state.emergency+f.reserveTransfer)/f.reserveTarget*100):100;return `<section class="wm-card wm-report-card"><span class="eyebrow">FONDASI LIKUIDITAS</span><div class="wm-profile-label">${short(f.reserveTarget)}</div><p>Target ${state.emergencyMonths} bulan × kebutuhan rutin ${fmt(f.expenses)}. Termasuk cicilan.</p><div class="wm-bar" role="img" aria-label="Cadangan awal setelah penyisihan ${Math.round(covered)} persen"><span style="width:${covered}%"></span></div>${detailList([['Cadangan yang sudah dipisahkan',fmt(state.emergency)],['Penyisihan awal dari kas / RDPU',fmt(f.reserveTransfer)],['Kekurangan setelah penyisihan',fmt(f.remainingGap)],['Perkiraan selesai dari anggaran',f.remainingGap<1?'Sudah tercukupi':f.budget>0?'Bulan ke-'+Math.ceil(f.remainingGap/f.budget):'Belum ada anggaran tersedia']])}<p class="wm-subtle">Jaga bagian yang perlu segera diakses di rekening likuid. RDPU tetap memiliki risiko dan waktu pencairan; tidak sama dengan uang tunai instan. Dana darurat diasumsikan tanpa pertumbuhan pada model.</p></section>`;}
  function allocationReport(r){const total=r.plannedSeed;let cursor=0;const gradient=r.capitalByAsset.map((v,i)=>{const start=cursor;cursor+=total?v/total*100:0;return `${E.ASSETS[i].color} ${start}% ${cursor}%`;}).join(',');
    const buckets=[r.capitalByAsset[0]+r.capitalByAsset[1],r.capitalByAsset[2]+r.capitalByAsset[3],r.capitalByAsset[4]+r.capitalByAsset[5]];
    return `<section class="wm-report-section"><div class="wm-report-heading"><div><h3>Bagaimana dana dibagi?</h3><p>Usulan modal awal yang ditetapkan ke tujuan. Dana darurat dan aset yang belum dialokasikan dihitung terpisah.</p></div></div><div class="wm-card"><div class="wm-donut-layout"><div class="wm-donut" style="background:${total?'conic-gradient('+gradient+')':'#26303d'}" role="img" aria-label="Komposisi modal awal; angka lengkap tersedia di tabel"><div class="wm-donut-center"><small>MODAL TUJUAN</small><b>${short(total)}</b></div></div><div class="wm-table-wrap"><table class="wm-table"><caption class="sr-only">Alokasi modal dan setoran bulan pertama</caption><thead><tr><th>Instrumen</th><th>Bobot</th><th>Modal awal</th><th>Setoran bulan 1</th></tr></thead><tbody>${E.ASSETS.map((a,i)=>`<tr><td><span class="wm-asset-label"><i class="wm-dot" style="background:${a.color}"></i>${esc(labelAsset(a.id))}</span></td><td>${pc(total?r.capitalByAsset[i]/total*100:0)}</td><td>${fmt(r.capitalByAsset[i])}</td><td>${fmt(r.monthlyByAsset[i])}</td></tr>`).join('')}</tbody></table></div></div><div class="wm-buckets">${buckets.map((v,i)=>`<div class="wm-bucket"><small>${['Likuiditas · kas & RDPU','Pendapatan tetap · RDPT & SBN','Ekuitas · RDS & saham'][i]}</small><b>${pc(total?v/total*100:0)}</b></div>`).join('')}</div><p class="wm-subtle">Setoran bulan pertama dapat nol karena cadangan darurat didahulukan. Bobot total merupakan gabungan tujuan, bukan formula tunggal berdasarkan usia. Ini pembagian kategori sederhana; komposisi sebenarnya perlu dibaca pada portofolio produk.</p><p class="wm-subtle">Reksa dana campuran dapat menjadi alternatif pengganti sebagian kombinasi pendapatan tetap dan saham setelah mengecek komposisinya. Jangan menambahkannya di atas alokasi ini tanpa mengurangi porsi lain.</p></div></section>`;
  }
  function goalsReport(r){return `<section class="wm-report-section"><div class="wm-report-heading"><div><h3>Rencana untuk setiap tujuan.</h3><p>Target memperhitungkan inflasi. Setoran dibagi sesuai prioritas dan surplus yang tersedia.</p></div></div>${r.goals.map(g=>{const funded=g.gap<=Math.max(1,g.target*1e-8);const add=g.months>0?g.gap/Math.pow(1+g.rates.base/100,g.months/12):g.gap;return `<article class="wm-goal-result"><div class="wm-result-heading"><div><h4>${esc(g.name)}</h4><p>Prioritas ${g.priority} · ${g.months===0?'Mulai sekarang':num.format(g.months/12)+' tahun'} · inflasi tujuan ${pc(g.inflation)}</p></div><span class="wm-status ${funded?'':'warning'}">${funded?'Memadai pada skenario dasar':'Perlu penyesuaian'}</span></div><div class="wm-goal-numbers"><div><small>Target pada tenggat</small><b>${fmt(g.target)}</b></div><div><small>Proyeksi dasar</small><b>${fmt(g.base)}</b></div><div><small>Kekurangan dana</small><b class="${funded?'positive':'gold'}">${fmt(g.gap)}</b></div><div><small>Setoran pertama yang tersedia</small><b>${fmt(g.firstPayment)}</b></div></div><div class="wm-weight-line" role="img" aria-label="Alokasi ${esc(g.name)}">${g.weights.map((w,i)=>w?`<span style="width:${w}%;background:${E.ASSETS[i].color}"></span>`:'').join('')}</div><div class="wm-weight-legend">${g.weights.map((w,i)=>w?`<span><i class="wm-dot" style="background:${E.ASSETS[i].color}"></i>${esc(labelAsset(E.ASSETS[i].id))} ${w}%</span>`:'').join('')}</div><div class="wm-goal-explanation"><strong>Mengapa pembagian ini?</strong> ${g.horizonNote}<br>Modal awal ${fmt(g.seed)} · total setoran ${fmt(g.paid)} · asumsi return dasar ${pc(g.rates.base)}/tahun. ${g.firstPaymentMonth!==null?'Setoran mulai bulan ke-'+g.firstPaymentMonth+'.':'Belum ada setoran yang dialokasikan.'}<br>Setoran pembanding jika tujuan berdiri sendiri dan dibayar setiap bulan sampai tenggat (mengabaikan usia akhir setoran): <strong>${g.theoretical===null?'Tidak dapat dicapai dengan setoran masa depan karena tenggatnya sekarang.':fmt(g.theoretical)+'/bulan.'}</strong>${!funded?`<br><strong>Pilihan yang dapat dibahas:</strong> tambah modal awal sekitar ${fmt(add)} bila arus setoran tetap; atau tinjau anggaran, biaya target, dan tenggat yang memang bisa diubah. Dana tambahan belum dianggap tersedia oleh simulator.`:''}</div></article>`;}).join('')}</section>`;}
  function chartSvg(g){
    if(g.months===0)return `<p class="wm-assumption-note">Tujuan ini dimulai sekarang. Bandingkan modal yang sudah tersedia dengan kebutuhan awal; tidak ada periode menabung sebelum tenggat.</p>`;
    const data=g.series, width=740,height=270,left=66,right=20,top=15,bottom=37;
    const max=Math.max(g.target,...data.flatMap(d=>[d.high,d.base,d.low,d.paid]),1)*1.1;
    const x=m=>left+m/g.months*(width-left-right),y=v=>height-bottom-v/max*(height-top-bottom);
    const path=key=>data.map((d,i)=>(i?'L':'M')+x(d.month).toFixed(2)+','+y(d[key]).toFixed(2)).join(' ');
    return `<svg class="wm-chart" viewBox="0 0 ${width} ${height}" role="img" aria-label="Proyeksi nilai nominal ${esc(g.name)}. Tabel angka tersedia di bawah grafik."><title>Proyeksi ${esc(g.name)}</title>${[0,1,2,3,4].map(i=>{const v=max*i/4;return `<line x1="${left}" x2="${width-right}" y1="${y(v)}" y2="${y(v)}" stroke="#8b97a422"/><text x="${left-10}" y="${y(v)+3}" text-anchor="end">${esc(short(v))}</text>`;}).join('')}<path class="target" d="M${left},${y(g.target)} L${width-right},${y(g.target)}"/>${[['high','#77cdb3'],['base','#ddbd8b'],['low','#ee9b9b'],['paid','#8393a8']].map(([key,color])=>`<path d="${path(key)}" stroke="${color}" ${key==='paid'?'stroke-dasharray="4 5"':''}/>`).join('')}${[0,1,2,3,4].map(i=>`<text x="${x(g.months*i/4)}" y="${height-10}" text-anchor="middle">${num.format(g.months/12*i/4)} th</text>`).join('')}</svg>`;
  }
  function chartReport(r){const g=r.goals.find(g=>g.id===selectedGoal)||r.goals[0];selectedGoal=g.id;
    return `<section class="wm-report-section" id="projectionSection"><div class="wm-report-heading"><div><h3>Lihat perjalanan dananya.</h3><p>Tiga skenario ilustratif, dengan arus setoran yang sama.</p></div><label><span class="sr-only">Pilih tujuan untuk grafik</span><select id="chartGoal">${r.goals.map(x=>`<option value="${esc(x.id)}" ${x.id===g.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label></div><div class="wm-card"><div class="wm-chart-legend">${[['Rendah','#ee9b9b'],['Dasar','#ddbd8b'],['Tinggi','#77cdb3'],['Modal + setoran','#8393a8'],['Target','#a5acb5']].map(([l,c])=>`<span><i class="wm-dot" style="background:${c}"></i>${l}</span>`).join('')}</div>${chartSvg(g)}<div class="wm-scenarios">${['low','base','high'].map((key,i)=>`<div class="wm-scenario"><small>${['Skenario rendah','Skenario dasar','Skenario tinggi'][i]} · ${pc(g.rates[key])}/tahun</small><b style="color:${['#ee9b9b','#ddbd8b','#77cdb3'][i]}">${fmt(g[key])}</b><p>${g.target>0?pc(g[key]/g.target*100)+' dari target':'Kebutuhan bersih target nol'}</p></div>`).join('')}</div><p class="wm-test-notice">Daya beli proyeksi dasar dalam uang hari ini: <b>${fmt(g.base/Math.pow(1+state.assumptions.inflation/100,g.months/12))}</b>, menggunakan inflasi umum ${pc(state.assumptions.inflation)}. Skenario bukan batas hasil terbaik/terburuk dan tidak menyatakan peluang keberhasilan.</p><details class="wm-chart-data"><summary>Lihat tabel tahunan lengkap</summary><div class="wm-table-wrap"><table class="wm-table"><thead><tr><th>Tahun</th><th>Modal + setoran</th><th>Rendah</th><th>Dasar</th><th>Tinggi</th></tr></thead><tbody>${g.series.map(d=>`<tr><td>${num.format(d.month/12)}</td><td>${fmt(d.paid)}</td><td>${fmt(d.low)}</td><td>${fmt(d.base)}</td><td>${fmt(d.high)}</td></tr>`).join('')}</tbody></table></div></details></div></section>`;
  }
  function retirementReport(r){return r.goals.filter(g=>g.retirement).map(g=>{
    const monthlyGap=g.retirement.monthlyGap,capital=g.base,inf=g.inflation/100;
    const costs=(from,to)=>{let total=0;for(let m=from;m<to;m++)total+=monthlyGap*Math.pow(1+inf,m/12);return total;};
    const first=Math.min(capital,costs(0,Math.min(24,g.retirement.periods)));
    const second=Math.min(Math.max(0,capital-first),costs(Math.min(24,g.retirement.periods),Math.min(60,g.retirement.periods)));
    const remaining=Math.max(0,capital-first-second),path=g.retirementPath;
    return `<section class="wm-report-section"><div class="wm-report-heading"><div><h3>Sesudah pensiun, bagaimana?</h3><p>${esc(g.name)} · mulai usia ${g.retireAge}, disimulasikan sampai usia ${g.endAge}.</p></div></div><div class="wm-card"><div class="wm-retirement-highlight"><div><small>Kebutuhan bersih bulanan saat mulai pensiun</small><b>${fmt(monthlyGap)}</b></div><div><small>Return nominal / riil masa pensiun</small><b>${pc(state.assumptions.retirementReturn)} / ${pc(g.retirement.realReturn)}</b></div><div><small>Dengan dana yang diproyeksikan tersedia</small><b>${path.depleted===null?'Bertahan sampai usia '+g.endAge:'Mulai kekurangan sekitar usia '+num.format(path.depleted)}</b></div></div><div class="wm-buckets"><div class="wm-bucket"><small>Cadangan penarikan hingga 24 bulan</small><b>${short(first)}</b><p class="wm-subtle">Kas / RDPU dengan likuiditas yang dipahami.</p></div><div class="wm-bucket"><small>Cadangan kebutuhan tahun 3–5</small><b>${short(second)}</b><p class="wm-subtle">Pertimbangkan pendapatan tetap sesuai jatuh tempo.</p></div><div class="wm-bucket"><small>Sisa untuk kebutuhan setelahnya</small><b>${short(remaining)}</b><p class="wm-subtle">Bauran aset sesuai profil dan kebutuhan penarikan.</p></div></div><p class="wm-subtle">Pembagian cadangan di atas adalah sketsa operasional dari proyeksi dasar, bukan dana tambahan. Perhitungan penarikan memakai return masa pensiun tetap ${pc(state.assumptions.retirementReturn)}, belum dihitung ulang dari bauran produk aktual. Tidak ada asumsi warisan akhir, kenaikan biaya medis khusus, atau risiko urutan return.</p><details class="wm-chart-data"><summary>Lihat proyeksi penarikan pensiun tahunan</summary><div class="wm-table-wrap"><table class="wm-table"><thead><tr><th>Usia</th><th>Kebutuhan bersih setahun</th><th>Sisa dana proyeksi</th></tr></thead><tbody>${path.rows.map(x=>`<tr><td>${x.age}</td><td>${fmt(x.annualSpend)}</td><td>${fmt(x.balance)}</td></tr>`).join('')}</tbody></table></div></details></div></section>`;
  }).join('');}
  function stressReport(r){return `<section class="wm-report-section"><div class="wm-report-heading"><div><h3>Jika pasar bergerak berlawanan.</h3><p>Uji tekanan hipotetis satu kali terhadap modal awal yang dialokasikan, tanpa setoran berikutnya.</p></div></div><div class="wm-report-grid"><div class="wm-card wm-report-card"><h3>Perubahan nilai modal awal</h3><div class="wm-profile-label negative">−${fmt(r.stressLoss)}</div><p>${pc(r.plannedSeed?r.stressLoss/r.plannedSeed*100:0)} dari modal ${fmt(r.plannedSeed)}. Sisa nilai ilustrasi ${fmt(r.plannedSeed-r.stressLoss)}. Ini bukan batas maksimum kerugian.</p></div><div class="wm-card wm-report-card"><h3>Hal yang perlu dipastikan</h3><ul class="wm-observations"><li>Apakah kebutuhan dekat tetap dapat dipenuhi tanpa menjual saat harga turun?</li><li>Jika jumlah penurunan ini terasa terlalu besar, tinjau jawaban profil risiko dan usulan alokasi.</li><li>Obligasi langsung dan reksa dana obligasi memiliki karakter likuiditas serta risiko harga yang berbeda.</li></ul></div></div></section>`;}
  function instrumentReport(){const notes={cash:'Sediakan dana transaksi dan kebutuhan yang harus segera dapat diakses.',rdpu:'Periksa komposisi, likuiditas, jadwal pencairan, biaya, dan riwayat risiko.',rdpt:'Periksa durasi, kualitas kredit, konsentrasi, serta kecocokan dengan tenggat.',sbn:'ORI/SR dapat diperdagangkan sesuai ketentuan. SBR/ST tidak diperdagangkan; fasilitas pencairan dini mengikuti syarat seri.',rds:'Periksa strategi, konsentrasi, biaya, dan konsistensi proses manajer investasi.',saham:'Tinjau bisnis, valuasi, likuiditas saham, diversifikasi, serta kemampuan memantau.'};return `<section class="wm-report-section"><div class="wm-report-heading"><div><h3>Dari alokasi ke pilihan instrumen.</h3><p>Kriteria untuk diskusi pemilihan produk; tidak ada nama produk atau emiten yang dipilih otomatis.</p></div></div><div class="wm-instruments">${E.ASSETS.map(a=>`<article class="wm-card wm-instrument"><i class="wm-dot" style="background:${a.color}"></i><h4>${esc(labelAsset(a.id))}</h4><p>${esc(a.note)}</p><small>${esc(notes[a.id])}</small></article>`).join('')}</div>${state.preference==='syariah'?'<p class="wm-subtle">Preferensi syariah memerlukan pemilihan produk dan efek yang memenuhi ketentuan syariah terkini. Mengubah label pada simulator tidak memverifikasi status syariah suatu produk.</p>':''}</section>`;}
  function auditReport(r){const f=r.f;return `<section class="wm-report-section"><details class="wm-chart-data"><summary>Ringkasan input, asumsi, dan setoran untuk ditinjau</summary><div class="wm-card"><h3 style="font-size:15px;margin-bottom:20px">Catatan dasar rencana</h3><div class="wm-table-wrap"><table class="wm-table"><tbody>${[['Usia / tanggungan',state.age+' tahun / '+state.dependents],['Penghasilan bersih bulanan',fmt(state.income)],['Pengeluaran di luar cicilan',fmt(state.expenses)],['Cicilan bulanan',fmt(state.debtPayment)],['Anggaran pilihan / yang digunakan',fmt(state.budget)+' / '+fmt(f.budget)],['Setoran rutin sampai usia',state.contributionEndAge+' tahun'],['Saldo utang',fmt(state.debtBalance)],['Total aset finansial termasuk dana darurat',fmt(f.financial)],['Aset noninvestasi',fmt(state.otherAssets)],['Kekayaan bersih',fmt(f.netWorth)],['Preferensi instrumen',state.preference==='syariah'?'Syariah':'Konvensional / tanpa pembatasan'],['Perlindungan kesehatan / jiwa',esc(state.healthCover)+' / '+esc(state.lifeCover)],['Inflasi umum / return masa pensiun',pc(state.assumptions.inflation)+' / '+pc(state.assumptions.retirementReturn)],...E.ASSETS.map(a=>['Asumsi return bersih '+a.name,pc(state.assumptions.returns[a.id])+'/tahun'])].map(([l,v])=>`<tr><td>${l}</td><td>${v}</td></tr>`).join('')}</tbody></table></div><p class="wm-subtle">Arus setoran di bawah dibatasi anggaran ${fmt(f.budget)}/bulan sampai usia ${state.contributionEndAge}. Setelah suatu tujuan selesai, kelebihan anggaran hanya digunakan untuk tujuan aktif yang masih memerlukan setoran. Sisanya tidak diberi pertumbuhan dalam proyeksi.</p><div class="wm-table-wrap" style="margin-top:15px"><table class="wm-table"><thead><tr><th>Periode</th><th>Dana darurat</th><th>Setoran tujuan</th><th>Anggaran tersisa</th></tr></thead><tbody>${yearlyCashflows(r).map(row=>`<tr><td>Tahun ${row.year}</td><td>${fmt(row.emergency)}</td><td>${fmt(row.goals)}</td><td>${fmt(row.unused)}</td></tr>`).join('')||'<tr><td colspan="4">Semua tujuan dimulai sekarang; tidak ada masa akumulasi.</td></tr>'}</tbody></table></div></div></details></section>`;}
  function yearlyCashflows(r){const years=[];for(const m of r.sim.totals){const index=Math.floor((m.month-1)/12);if(!years[index])years[index]={year:index+1,emergency:0,goals:0,unused:0};for(const k of ['emergency','goals','unused'])years[index][k]+=m[k];}return years;}
  function report(){
    const r=E.calculate(state);if(r.errors.length){showErrors(r.errors);return '<p class="wm-subtle">Perbaiki data yang ditandai, lalu hitung ulang rencana.</p>';}
    result=r;
    return `<div class="wm-report-top"><div><span class="eyebrow">RENCANA KEUANGAN PERSONAL</span><h2>${esc(state.alias||'Rencana keuangan kamu')}</h2><p>${state.demo?'Data contoh · ':''}${new Intl.DateTimeFormat('id-ID',{dateStyle:'long',timeZone:'Asia/Jakarta'}).format(new Date())} · Usulan awal untuk ditinjau bersama</p></div><div class="wm-report-actions"><button class="button" id="printPlan">${icon('file')}Cetak / simpan PDF</button><button class="button" id="revisePlan">${icon('sliders')}Ubah data</button></div></div>
    <p class="wm-print-only">TAKTIKSAHAM Wealth Management · Simulasi edukatif, bukan jaminan hasil atau rekomendasi produk final. Data ${state.demo?'contoh nasabah':'sesuai input pengguna'}.</p>
    <div class="wm-kpis"><article class="wm-kpi"><small>Kekayaan bersih</small><b>${short(r.f.netWorth)}</b><p>Aset finansial + aset lain − utang.</p></article><article class="wm-kpi accent"><small>Anggaran yang bisa digunakan</small><b>${short(r.f.budget)}</b><p>Per bulan, termasuk pengisian cadangan.</p></article><article class="wm-kpi"><small>Kebutuhan anggaran model</small><b>${r.required===null?'Modal tambahan':short(r.required)}</b><p>${r.required===null?'Periode setoran / modal saat ini belum dapat memenuhi kebutuhan.':'Per bulan selama masa setoran agar seluruh target dasar terpenuhi dalam model.'}</p></article><article class="wm-kpi"><small>Tujuan memadai pada dasar</small><b>${r.funded}<span style="font-size:15px;color:var(--muted)"> / ${r.goals.length}</span></b><p>Bukan probabilitas keberhasilan.</p></article></div>
    ${r.shortfall>1?`<div class="wm-assumption-note">Kebutuhan anggaran model melebihi kemampuan saat ini sebesar <b>${fmt(r.shortfall)}/bulan</b>. Tinjau sumber dana tambahan, prioritas, atau besarnya tujuan; jangan menaikkan asumsi return hanya agar target terlihat tercapai.</div>`:''}
    <div class="wm-report-grid">${profileCard(r)}${emergencyCard(r)}</div>
    <section class="wm-card wm-report-card"><h3>Yang perlu didahulukan</h3><ul class="wm-observations">${observations(r).map(t=>`<li>${esc(t)}</li>`).join('')}</ul></section>
    ${allocationReport(r)}${goalsReport(r)}${chartReport(r)}${retirementReport(r)}${stressReport(r)}${instrumentReport()}
    <section class="wm-report-section"><div class="wm-report-heading"><div><h3>Langkah implementasi yang terukur.</h3><p>Hasil simulator menjadi bahan diskusi; perpindahan aset dan transaksi tidak dilakukan otomatis.</p></div></div><div class="wm-roadmap"><article class="wm-card"><span>01 / 30 HARI PERTAMA</span><h4>Rapikan fondasi</h4><p>Validasi input, saldo aset, kewajiban, dan proteksi. Pisahkan dana darurat. Tentukan prioritas yang benar-benar perlu didanai.</p></article><article class="wm-card"><span>02 / BULAN 2–3</span><h4>Terapkan bertahap</h4><p>Tinjau instrumen sesuai profil, likuiditas, dan jatuh tempo. Terapkan setoran setelah memeriksa minimum pembelian serta biaya aktual.</p></article><article class="wm-card"><span>03 / SETIAP 6–12 BULAN</span><h4>Evaluasi & sesuaikan</h4><p>Bandingkan saldo aktual dengan target. Tinjau alokasi saat kondisi hidup berubah atau bobot menyimpang, misalnya 5 poin persentase. Kurangi risiko saat tujuan mendekat.</p></article></div></section>
    ${auditReport(r)}
    <section class="wm-callout"><div><span class="eyebrow" style="margin-bottom:12px">LANGKAH BERIKUTNYA</span><h3>Diskusikan rencanamu secara personal.</h3><p>Bawa hasil ini untuk membahas prioritas dan pilihan instrumen. Data keuangan tidak disertakan dalam pesan WhatsApp kecuali kamu memilihnya.</p><label class="wm-check"><input type="checkbox" id="includeSummary"><span>Sertakan ringkasan profil, modal tujuan, anggaran, dan nama tujuan dalam pesan WhatsApp.</span></label></div><aside><a class="button primary" id="consultLink" href="${waLink(false)}" target="_blank" rel="noopener">${icon('message')}Diskusi lewat WhatsApp</a><a class="button" href="https://login.miraeasset.co.id/registration/oe?referralcode=3103248" target="_blank" rel="noopener">Buka rekening Mirae ${icon('up')}</a><small>0856-9748-6266 · Referral 3103248</small></aside></section>
    <div class="wm-local-controls"><button class="button small" id="saveLocal">Simpan di perangkat ini</button><button class="button small" id="deleteLocal">Hapus simpanan perangkat</button><p>Simpanan lokal tidak terenkripsi. Hindari menyimpan data nasabah pada perangkat bersama. Unduh file untuk membawa rencana ke perangkat lain.</p></div>
    <div class="wm-print-only"><b>Dasar hitung:</b> Modal tujuan ${fmt(r.plannedSeed)}; dana darurat ${fmt(r.f.reserveTarget)} dipisahkan; setoran akhir bulan dibatasi surplus sampai usia ${state.contributionEndAge}. Target mengikuti inflasi tiap tujuan; return akumulasi bersih tetap, hasil diinvestasikan kembali. Pensiun memakai penarikan awal bulan, inflasi biaya, dan return masa pensiun ${pc(state.assumptions.retirementReturn)}. Skenario bukan probabilitas; tidak memodelkan risiko urutan return, transaksi riil, pajak khusus, perubahan penghasilan, atau warisan. Kaji ulang data, proteksi, kebutuhan likuiditas, prospektus, dan biaya produk sebelum implementasi. Referensi: OJK Buku Saku Cerdas Mengelola Keuangan; BEI Reksa Dana; DJPPR SBN Ritel. Metode lengkap tersedia pada halaman simulator.</div>`;
  }
  function waLink(include){let text='Halo, saya ingin mendiskusikan hasil simulasi Wealth Management TAKTIKSAHAM dan langkah investasi melalui referral 3103248.';if(include&&result){text+='\nProfil model: '+result.risk.label+'\nModal tujuan: '+fmt(result.plannedSeed)+'\nAnggaran bulanan: '+fmt(result.f.budget)+'\nTujuan: '+result.goals.map(g=>g.name).join(', ')+'.\nHasil ini simulasi awal, mohon bantu ditinjau.';}return 'https://wa.me/6285697486266?text='+encodeURIComponent(text);}
  function showErrors(errors){const el=$('#formErrors');el.hidden=!errors.length;el.innerHTML=errors.length?'<b>Data perlu diperbaiki</b><ul>'+errors.map(t=>'<li>'+esc(t)+'</li>').join('')+'</ul>':'';if(errors.length)el.focus();}
  function render(){showErrors([]);$('#demoBanner').hidden=!state.demo;$$('[data-step]').forEach(b=>{const active=Number(b.dataset.step)===step;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');});$('#plannerContent').innerHTML=[finances,goalsForm,riskForm,assumptionsForm,report][step]();$('#prevStep').disabled=step===0;$('#nextStep').innerHTML=step===4?'Ubah kondisi '+icon('sliders'):['Lanjut ke tujuan','Lanjut ke profil risiko','Tinjau asumsi','Lihat rencana lengkap'][step]+' '+icon('arrow');$('#stepHint').textContent='Langkah '+(step+1)+' dari 5';}
  function move(next){if(next===4){const errors=E.validate(state);if(errors.length){showErrors(errors);return;}}step=next;render();$('#plannerContent').focus({preventScroll:true});$('.wm-stepper').scrollIntoView?.({behavior:'smooth',block:'start'});}
  function download(text,filename,type='application/json'){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);}
  function sanitizedImport(raw){if(!raw||raw.version!==1)throw new Error('Versi file rencana tidak didukung.');const errors=E.validate(raw,{allowDraft:true});if(errors.length)throw new Error(errors[0]);return E.clone(raw);}
  document.addEventListener('input',e=>{const el=e.target,path=el.dataset?.path;if(!path)return;let value;if(el.type==='checkbox')value=el.checked;else if(el.type==='number'||el.type==='radio'||path.endsWith('.priority'))value=Number(el.value);else value=el.value;pathSet(path,value);state.demo=false;result=null;$('#demoBanner').hidden=true;showErrors([]);const line=$('[data-money-for="'+path+'"]');if(line)line.textContent=fmt(Number(value));if(step===0&&$('#financeSummary'))$('#financeSummary').innerHTML=financialSummary(E.foundation(state));if(path.startsWith('assumptions.returns.')){const key=path.split('.').at(-1);$('[data-low="'+key+'"]').textContent=pc(value-E.LOW[key]);$('[data-high="'+key+'"]').textContent=pc(value+E.HIGH[key]);}});
  document.addEventListener('change',e=>{const el=e.target,path=el.dataset?.path;if(path&&path.startsWith('goals.')&&path.endsWith('.type')){const g=state.goals[Number(path.split('.')[1])];g.type=el.value;if(g.type==='retirement'){g.retireAge=Math.max(state.age,60);g.endAge=Math.max(g.retireAge+20,85);g.spending=state.expenses;g.pension=0;}else{g.years=Math.max(1,g.years||5);g.amount=Math.max(1,g.amount||100000000);}render();}if(el.id==='chartGoal'){selectedGoal=el.value;const replacement=document.createElement('div');replacement.innerHTML=chartReport(result);$('#projectionSection').replaceWith(replacement.firstElementChild);}if(el.id==='includeSummary')$('#consultLink').setAttribute('href',waLink(el.checked));});
  document.addEventListener('click',e=>{const button=e.target.closest('button');if(!button)return;
    if(button.dataset.step!==undefined){move(Number(button.dataset.step));return;}
    if(button.dataset.example){state=E.example(Number(button.dataset.example));selectedGoal=null;step=0;result=null;render();toast('Contoh dimuat. Ini bukan data nasabah.');return;}
    if(button.dataset.removeGoal!==undefined){state.goals.splice(Number(button.dataset.removeGoal),1);state.demo=false;result=null;render();return;}
    switch(button.id){
      case 'nextStep':move(step===4?0:step+1);break;
      case 'prevStep':move(Math.max(0,step-1));break;
      case 'revisePlan':move(0);break;
      case 'addGoal':if(state.goals.length<6){state.goals.push({id:'g'+Date.now(),name:'Tujuan baru',type:'other',years:5,amount:100000000,inflation:state.assumptions.inflation,seed:0,priority:3});state.demo=false;result=null;render();}break;
      case 'startFresh':state=E.clone(E.defaults);state.demo=false;state.alias='Rencana keuangan saya';state.age=30;state.dependents=0;for(const k of ['income','expenses','debtPayment','debtBalance','budget','emergency','otherAssets'])state[k]=0;for(const a of E.ASSETS)state.assets[a.id]=0;state.healthCover='review';state.lifeCover='review';state.risk={loss:null,reaction:null,experience:null,goal:null,fluctuation:null,effort:null};state.goals=[{id:'g1',name:'Tujuan pertama',type:'other',years:5,amount:100000000,inflation:4,seed:0,priority:1}];selectedGoal=null;step=0;result=null;render();toast('Rencana baru. Isi kondisi dan seluruh pertanyaan risiko.');break;
      case 'savePlan':{const errors=E.validate(state,{allowDraft:true});if(errors.length){showErrors(errors);break;}download(JSON.stringify({...state,version:1},null,2),'TAKTIKSAHAM-rencana-wealth.json');toast('File rencana diunduh. File memuat angka keuangan yang kamu isi.');break;}
      case 'saveLocal':try{localStorage.setItem(STORE,JSON.stringify(state));toast('Rencana tersimpan di browser perangkat ini.');}catch(_){toast('Browser tidak mengizinkan penyimpanan. Gunakan Unduh rencana.');}break;
      case 'loadLocal':try{const saved=localStorage.getItem(STORE);if(!saved){toast('Belum ada rencana yang disimpan di perangkat ini.');break;}state=sanitizedImport(JSON.parse(saved));step=0;result=null;selectedGoal=null;render();toast('Simpanan perangkat dibuka.');}catch(err){toast('Simpanan belum dapat dibuka: '+err.message);}break;
      case 'deleteLocal':try{localStorage.removeItem(STORE);toast('Simpanan perangkat dihapus. Rencana yang sedang dibuka tetap ada sampai tab ditutup.');}catch(_){toast('Penyimpanan perangkat tidak dapat diakses.');}break;
      case 'printPlan':$$('.wm-chart-data').forEach(d=>d.open=true);window.print();break;
    }
  });
  $('#importPlan').addEventListener('change',async e=>{const input=e.target,file=input.files?.[0];if(!file)return;try{if(file.size>1024*1024)throw new Error('Ukuran file maksimal 1 MB.');state=sanitizedImport(JSON.parse(await file.text()));step=0;result=null;selectedGoal=null;render();toast('Rencana diimpor. Periksa kembali data sebelum menghitung.');}catch(err){toast('Impor tidak berhasil: '+err.message);}input.value='';});
  window.TSWealth={getState:()=>E.clone(state),getResult:()=>result,goTo:move};
  render();
})();
